In [1]:
print("helloWorld")

helloWorld


In [3]:
listA = [1,2,3,4,5]
listB = [2,3,4,5,6]
for i in listA:
    print(i)
for i in listB:
    print(i)

1
2
3
4
5
2
3
4
5
6


In [4]:
print(listA)

[1, 2, 3, 4, 5]


In [5]:
import numpy as np

In [6]:
np_array1 = np.array([[1,2,3],[4,5,6]])

In [7]:
print(np_array1)

[[1 2 3]
 [4 5 6]]


In [8]:
print(type(np_array1))

<class 'numpy.ndarray'>


In [11]:
np_array2 = np.array([[2,3],[4,5],[1,2]])

In [12]:
print(np_array1)
print(np_array2)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [4 5]
 [1 2]]


In [13]:
# 矩阵相乘
print(np.dot(np_array1,np_array2))

[[13 19]
 [34 49]]


In [14]:
na1 = np.array(["1","2","3"])

In [15]:
print(na1)

['1' '2' '3']


In [16]:
print(na1.astype("int"))

[1 2 3]


In [17]:
print(np_array1)

[[1 2 3]
 [4 5 6]]


In [18]:
print(np_array1[0])

[1 2 3]


In [19]:
print(np_array1[1][1])

5


In [21]:
print(np_array1[:,1])

[2 5]


In [23]:
na2 = np.array([[1,2,3,3],[4,5,6,7],[7,8,9,1],[10,11,12,13]])
print(na2)

[[ 1  2  3  3]
 [ 4  5  6  7]
 [ 7  8  9  1]
 [10 11 12 13]]


In [24]:
# ndarray 使用时可以当作 python 原生的list来使用
# 在使用索引的时候可以 分别传入 行的索引 和 列的索引，中间以","分割
# 切片索引
print(na2[1:3,1:3])

[[5 6]
 [8 9]]


In [25]:
print(na2)

[[ 1  2  3  3]
 [ 4  5  6  7]
 [ 7  8  9  1]
 [10 11 12 13]]


In [31]:
list1 = [[0,1,2,3],[0,1,2,3]]
print(na2[list1])

[ 1  5  9 13]


c:\users\zzk10\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


print(na2)

In [34]:
print(na2)
# 布尔索引
print(na2>6)

[[ 1  2  3  3]
 [ 4  5  6  7]
 [ 7  8  9  1]
 [10 11 12 13]]
[[False False False False]
 [False False False  True]
 [ True  True  True False]
 [ True  True  True  True]]


In [35]:
print(na2[na2>6])

[ 7  7  8  9 10 11 12 13]


In [36]:
na3 = np.array([[1,2,3],[4,5,6]])
print(na3)

[[1 2 3]
 [4 5 6]]


In [37]:
na4 = np.array([[1,2,3],[5,6,7]])

In [38]:
print(na4)

[[1 2 3]
 [5 6 7]]


In [46]:
# reshape 会返回一个新的 array 并不会改变原来的
na4_reshape = na4.reshape(3,2)

In [48]:
na4_reshape = na4.reshape(3,2)
# 矩阵相乘 需要 使用 np的dot方法
print(np.dot(na3,na4_reshape))

[[25 33]
 [55 75]]


In [49]:
print(na3)
print(na4)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 6 7]]


In [51]:
# 按位乘
print(na3*na4)
# 按位+
print(na3+na4)

[[ 1  4  9]
 [20 30 42]]
[[ 2  4  6]
 [ 9 11 13]]


In [52]:
# 矩阵相加 相当于按位加
print(np.add(na3,na4))

[[ 2  4  6]
 [ 9 11 13]]


In [54]:
print(na3)
print(na4)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 6 7]]


In [57]:
# 延纵轴拼接
print(np.vstack((na3[0],na4[1])))
# 延横轴拼接
print(np.hstack((na3[0],na4[1])))

[[1 2 3]
 [5 6 7]]
[1 2 3 5 6 7]


In [58]:
print(na3)

[[1 2 3]
 [4 5 6]]


In [60]:
# 矩阵的反转
print(na3.T)
# 矩阵的转置
print(na3.transpose())

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [61]:
print(na3)

[[1 2 3]
 [4 5 6]]


In [63]:
# 左右翻转
print(np.fliplr(na3))
# 上下翻转
print(np.flipud(na3))

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [64]:
# 取对数
# log 函数会作用于矩阵的每一个元素
print(np.log(na3))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [65]:
a = np.array([1,3,4,5,8])
print(a)

[1 3 4 5 8]


In [66]:
print(np.diff(a,n=1,axis=-1))

[2 1 1 3]


In [70]:
# 求最大值
print(na3)
print(np.amax(na3))
# axis = 0 表示纵轴方向
# axis = 1 表示横轴方向
print(np.amax(na3,axis=0))
print(np.amax(na3,axis=1))

[[1 2 3]
 [4 5 6]]
6
[4 5 6]
[3 6]


In [71]:
# 平均值
print(np.mean(na3))

3.5
